# Generated by Django 5.0 on 2023-12-15 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='MainApi.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('descuento', models.IntegerField()),
                ('total', models.FloatField()),
                ('cantidad_disponibles', models.PositiveIntegerField()),
                ('cantidad_vendidos', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApi.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('total_original', models.PositiveIntegerField()),
                ('total_descuento', models.PositiveIntegerField()),
                ('total_final', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApi.producto')),
            ],
        ),
    ]
