# Generated by Django 5.0 on 2023-12-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_vendidos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
